export const testData = [
    {
        question: ' Which one of the following river flows between Vindhyan and Satpura ranges?',
        options: ['Narmada','Mahanadi','Son','Netravati',],
        correct: 1,
        marked: -1,
    },
    {
        question: 'The Central Rice Research Station is situated in?',
        options: ['Chennai','Cuttack','Bangalore','Quilon'],
        correct: 2,
        marked: -1,
    },
    {
        question: 'Who among the following wrote Sanskrit grammar?',
        options: ['Kalidasa','Charak','Panini','Aryabhatt'],
        correct: 3,
        marked: -1,
    },
    {
        question: 'Which among the following headstreams meets the Ganges in last?',
        options: ['Alaknanda','Pindar','Mandakini','Bhagirathi'],
        correct: 4,
        marked: -1,
    },
    {
        question: 'The metal whose salts are sensitive to light is?',
        options: ['Zinc','Silver','Copper','Aluminum'],
        correct: 2,
        marked: -1,
    },
    {
        question: 'Patanjali is well known for the compilation of –',
        options: ['Yoga Sutra','Panchatantra','Brahma Sutra','Ayurveda'],
        correct: 1,
        marked: -1,
    },
    {
        question: 'River Luni originates near Pushkar and drains into which one of the following?',
        options: [' Rann of Kachchh','Arabian Sea','Gulf of Cambay','Lake Sambhar'],
        correct: 1,
        marked: -1,
    },
    {
        question: 'Which one of the following rivers originates in Brahmagiri range of Western Ghats?',
        options: ['Pennar','Cauvery','Krishna','Tapti'],
        correct: 2,
        marked: -1,
    },
    {
        question: 'The country that has the highest in Barley Production?',
        options: ['China','India','Russia','France'],
        correct: 3,
        marked: -1,
    },
    {
        question: 'Tsunamis are not caused by',
        options: ['Hurricanes','Earthquakes','Undersea landslides','Volcanic eruptions'],
        correct: 1,
        marked: -1,
    },
    {
        question: 'Chambal river is a part of –',
        options: ['Sabarmati basin','Ganga basin','Narmada basin','Godavari basin'],
        correct: 3,
        marked: -1,
    },
    {
        question: 'D.D.T. was invented by?',
        options: ['Mosley','Rudolf','Karl Benz','Dalton'],
        correct: 1,
        marked: -1,
    },
    {
        question: 'Volcanic eruption do not occur in the',
        options: ['Baltic sea','Black sea','Caribbean sea','Caspian sea'],
        correct: 1,
        marked: -1,
    },
    {
        question: 'Indus river originates in –',
        options: ['Kinnaur','Ladakh','Nepal','Tibet'],
        correct: 4,
        marked: -1,
    },
    {
        question: ' The hottest planet in the solar system?',
        options: ['Mercury','Venus','Mars','Jupiter'],
        correct: 2,
        marked: -1,
    },
    {
        question: 'With which of the following rivers does Chambal river merge?',
        options: ['Banas','Ganga','Narmada','Yamuna'],
        correct: 4,
        marked: -1,
    },
    {
        question: 'Where was the electricity supply first introduced in India –',
        options: ['Mumbai','Dehradun','Darjeeling','Chennai'],
        correct: 3,
        marked: -1,
    },
    {
        question: 'Amravati, Bhavani, Hemavati and Kabini are tributaries of which one of the following rivers?',
        options: ['Mahanadi','Godawari','Cauvery','Krishna'],
        correct: 3,
        marked: -1,
    },
    {
        question: 'Which of the following is related to Bharat Nirman Scheme?',
        options: [' Foodgrain production self sufficiency','Family welfare programme','Infrastructure development','Employment generation program'],
        correct: 3,
        marked: -1,
    },
    {
        question: 'Which peninsular river is least seasonal in flow?',
        options: ['Narmada','Krishna','Godavari','Cauvery'],
        correct: 3,
        marked: -1,
    },
    {
        question: 'Which one of the following ports is the oldest port in India?',
        options: ['Mumbai Port','Chennai Port','Kolkata Port','Vishakhapatnam Port'],
        correct: 2,
        marked: -1,
    },
    {
        question: 'At which one of the following places do the rivers Alaknanda and Bhagirathi merge to form Ganga?',
        options: ['Devprayag','Rudra Prayag','Karnaprayag','Vishnuprayag'],
        correct: 1,
        marked: -1,
    },
    {
        question: 'Which of the following is not a nuclear power center?',
        options: ['Narora','Kota','Chamera','Kakrapara'],
        correct: 3,
        marked: -1,
    },
    {
        question: 'Gravity setting chambers are used in industries to remove',
        options: ['NOx','SOx','CO','suspended particulate matter'],
        correct: 4,
        marked: -1,
    },
    {
        question: 'First Afghan War took place in',
        options: ['1839','1848','1843','1833'],
        correct: 1,
        marked: -1,
    },
    {
        question: 'Hitler party which came into power in 1933 is known as',
        options: ['Ku-Klux-Klan','Democratic Party','Labour Party','Nazi Party'],
        correct: 4,
        marked: -1,
    },
    {
        question: 'Guwahati High Court is the judicature of',
        options: ['Assam','Nagaland','Arunachal Pradesh','All of the above'],
        correct: 4,
        marked: -1,
    },
    {
        question: 'Grand Central Terminal, Park Avenue, New York is the world’s',
        options: ['highest railway station','longest railway station','largest railway station','None of the above'],
        correct: 3,
        marked: -1,
    },
    {
        question: 'FFC stands for',
        options: ['Federation of Football Council','Film Finance Corporation','Foreign Finance Corporation','None of the above'],
        correct: 2,
        marked: -1,
    },
    {
        question: 'First China War was fought between',
        options: ['China and Egypt','China and Greek','China and Britain','China and France'],
        correct: 3,
        marked: -1,
    },
    
    
]